profiles/urls.py
from django.urls import path
from .views import(
    AdminPanelUserView,
    AdminPanelFilesView,
    AdminPanelFileManageView,
    rice_upload
)

app_name = 'profiles'

urlpatterns = [
    path('user_management/', AdminPanelUserView.as_view(), name='user-manage'),
    path('file_management/', AdminPanelFileManageView.as_view(), name='file-manage'),
    path('file_upload/', AdminPanelFilesView.as_view(), name='file_upload'),
    path('rice/upload/', rice_upload, name='rice_upload'),

]

rice/urls.py
from django.urls import path
from .views import(

    HomePageView,
    DocsPageView,
    rice_list_view,
    get_data_name,
    get_data_info,
    info_view,
    advanced_search_view,
    comparison_view,
    get_data_comparison_view,
    AboutPageView
)

app_name = 'rice'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('rice_list/',rice_list_view, name="searches"),
    path('get-data/',get_data_name),
    path('info/<int:pk>/',info_view, name="info-view"),
    path('get_data_info/<int:pk>/<str:fieldGroup>/',get_data_info, name ="data-info"),
    path('advanced_search/',advanced_search_view, name ="advanced-search"),
    path('comparison/',comparison_view, name ="comparison"),
    path('get_data_comparison/<str:fieldGroup>/',get_data_comparison_view, ),
    path('about/',AboutPageView.as_view(), name ="about"),
]

ricenutrition/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('admin_panel/', include('profiles.urls')),
    path('', include('rice.urls')),
]+ static(settings.STATIC_URL,
document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    institute = models.CharField(max_length=50)

rice/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL
# Create your models here.
class Files(models.Model):
    BIOACTIVE = 'BI'
    CHEMICAL = 'CH'
    SAMPLEINFO = 'SP'
    NUTRITION = 'NU'
    PHYSICAL = 'PH'
    META_DATA = 'MD'
    TYPE_FILE = [
        (BIOACTIVE, 'Bioactive'),
        (CHEMICAL, 'Chemical'),
        (SAMPLEINFO, 'Sampleinfo'),
        (NUTRITION, 'Nutrition'),
        (PHYSICAL, 'Physical'),
        (META_DATA, 'Meta Data'),
    ]
    type_file = models.CharField(
        max_length=2,
        choices=TYPE_FILE
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    upload = models.FileField(upload_to='rice/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

profiles/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.utils.translation import gettext, gettext_lazy as _

class CoreSignupForm(SignupForm):
    first_name = forms.CharField(
        label=_("First Name"),
        max_length=30,
        widget=forms.TextInput(
            attrs={"placeholder": _("First Name"), "autocomplete": "first_name"}
        ),
    )
    last_name = forms.CharField(
        label=_("Last Name"),
        max_length=30,
        widget=forms.TextInput(
            attrs={"placeholder": _("Last Name"), "autocomplete": "last_name"}
        ),
    )
    institute = forms.CharField(
        label=_("Institute"),
        max_length=30,
        widget=forms.TextInput(
            attrs={"placeholder": _("Institute"), "autocomplete": "institute"}
        ),
    )
    def custom_signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.institute = self.cleaned_data['institute']
        user.save()

profiles/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from allauth.account.models import EmailAddress,EmailConfirmation
from django.views.generic import TemplateView, UpdateView
from django.http import JsonResponse
from allauth.account.adapter import get_adapter
from .models import User
from rice.models import Files
from django.contrib import messages
from rice.utils import get_collection_handle, get_db_handle
from django.conf import settings
import openpyxl
import time
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin

def staff_check(user):
    return user.is_active and user.is_staff

class TestMixin1(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_active and self.request.user.is_staff

class AdminPanelUserView(TestMixin1, ListView):
    context_object_name = 'users'
    queryset = EmailAddress.objects.filter(primary = True).order_by('user')
    template_name = 'profiles/users_admin.html'

    def post(self, request, *args, **kwargs):
        selected = request.POST.getlist('id') or None
        action = request.POST.get('action') or None
        if(not selected):
            messages.warning(request, 'Items must be selected in order to perform actions on them. No items have been changed.')
        elif(not action):
            messages.warning(request, 'No action selected.')
        else:
            if action == 'approval_user':
                for item in selected:
                    pk = int(item)
                    email_address = EmailAddress.objects.get(user=pk)
                    email_address.send_confirmation(request)
                    messages.success(request, 'User details updated.')
        return HttpResponseRedirect(request.get_full_path())

class AdminPanelFileManageView(TestMixin1, ListView):
    context_object_name = 'files'
    queryset = Files.objects.all()
    template_name = 'profiles/file_manage_admin.html'

class AdminPanelFilesView(TestMixin1, TemplateView):
    template_name = 'profiles/files_admin.html'

@user_passes_test(staff_check)
def rice_upload(request):
    t0 = time.time()
    if request.method == 'POST':
        excel_file = request.FILES.get('file')
        type_file = request.POST['typeFile']
        type_file_first = {
            'BI': settings.FIRST_ROW_BIO,
            'CH': settings.FIRST_ROW_CHEM,
            'SP': settings.FIRST_ROW_SAMPLE,
            'NU': settings.FIRST_ROW_NUTRI,
            'PH': settings.FIRST_ROW_PHY,
        }

        if(type_file == 'MD'):
            db, _ = get_db_handle(settings.DB_NAME, settings.HOST_MONGODB )
            collection = get_collection_handle(db, settings.COLLECTION_NAME_META)
            wb = openpyxl.load_workbook(excel_file)
            worksheet = wb.active
            rows = worksheet.rows
            first_row = [cell.value for cell in next(rows)]
            for row in rows:
                record = {}
                for key, cell in zip(first_row, row):
                    record[key] = cell.value
                    collection.update({"fieldID":record["fieldID"]}, {"$set": record}, upsert = True)
            return JsonResponse({'ex': True})
        wb = openpyxl.load_workbook(excel_file)
        worksheet = wb.active
        rows = worksheet.rows
        first_row = [cell.value for cell in next(rows)]
        if(type_file_first[type_file] != first_row):
            return JsonResponse({'ex': False})
        else:
            obj = Files.objects.create(type_file=type_file, user=request.user,  upload=excel_file)
            a = obj.TYPE_FILE

            for row in a:
                if obj.type_file == row[0]:
                    coll = row[1]


            db, _ = get_db_handle(settings.DB_NAME, settings.HOST_MONGODB )
            collection = get_collection_handle(db, settings.COLLECTION_NAME)
            wb = openpyxl.load_workbook(obj.upload.path, read_only=True)
            worksheet = wb.active
            rows = worksheet.rows
            first_row = [cell.value for cell in next(rows)]
            nutri = collection.find({ coll: { '$exists': True } })
            nutri_list = list(nutri)
            for row in rows:
                record = {}
                for key, cell in zip(first_row, row):
                    if cell.data_type == 's':
                        record[key] = cell.value.strip()
                    elif isinstance(cell.value, float):
                        record[key] = float(cell.value)
                    else:
                        record[key] = cell.value
                if coll == 'Sampleinfo':
                    collection.update({'cropSampleID': record["cropSampleID"]},  {'$set': {'cropSampleID': record["cropSampleID"], coll: record}}, upsert = True)

                else:
                    # nutri = collection.find({'cropSampleID': record["cropSampleID"], f"{coll}.nutritionDBID": record['nutritionDBID']})
                    # nutri_list = list(nutri)

                    if nutri_list == []:
                        collection.update({'cropSampleID': record["cropSampleID"]},{'$push':{coll:record}}, upsert = True)
                    else:
                    # collection.update_one ({'cropSampleID': record["cropSampleID"]},{'$set':{f"{coll}.$[elem]":record}}, array_filters = [ { "elem.nutritionDBID": record['nutritionDBID'] } ])
                        collection.find_one_and_update({'cropSampleID': record["cropSampleID"]},{'$set':{f"{coll}.$[elem]":record}}, array_filters = [ { "elem.nutritionDBID": record['nutritionDBID'] } ], upsert = True)
    t1 = time.time()
    print(t1-t0)
    return JsonResponse({'ex': True })

profiles/templates/profiles/base_admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% block extra_head %}
  {% endblock %}
  <title>Admin Panel</title>
</head>


<body>
  <div class="loader"></div>
  {% block modal %}
  {% endblock %}


  <div class="gird-container">
    <div class="navigation">
      <div class="navigation__brand">
        <a href="/">
          <img src="{% static 'images/logo.png' %}" alt="logo">
          <div class="navigation__brand-name">
            <div>Thai Rice</div>
            <div>Nutrition Data</div>
          </div>
        </a>
      </div>
      <div class="navigation__block">
        <ul>
          <li>
            <a href="{% url 'profiles:user-manage' %}" {% if "/user_management/" in request.path %}class="active" {% endif %}>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people"
                viewBox="0 0 16 16">
                <path
                  d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z" />
              </svg>
              <span>User management</span>
            </a>
          </li>
          <li>
            <a href="{% url 'profiles:file-manage' %}" {% if "/file_management/" in request.path %}class="active" {% endif %}>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-file-earmark-diff" viewBox="0 0 16 16">
                <path
                  d="M8 5a.5.5 0 0 1 .5.5V7H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V8H6a.5.5 0 0 1 0-1h1.5V5.5A.5.5 0 0 1 8 5zm-2.5 6.5A.5.5 0 0 1 6 11h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z" />
                <path
                  d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z" />
              </svg>
              <span>File management</span>
            </a>
          </li>
          <li>
            <a href="{% url 'profiles:file_upload' %}" {% if "/file_upload/" in request.path %}class="active" {% endif %}>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
              </svg>
              <span>File Upload</span>
            </a>
          </li>

        </ul>
      </div>
    </div>
    {% block content %}
    {% endblock %}
  </div>
</body>
<script>
  let preloader = document.querySelector('.loader');
  if (preloader) {
    window.addEventListener('load', () => {
      preloader.remove()
    });
  }

</script>
{% block script %}
{% endblock %}

</html>

profiles/templates/profiles/file_manage_admin.html
{% extends "profiles/base_admin.html" %}
{% load static %}

{% block content %}
<main class="main">
  <div class="main__hero">
    <div class="page">
      <div class="page__title">
        <h2>Files management</h2>

      </div>
    </div>
    <div class="main__content">
      <table class="table">
        <thead>
          <tr>
            <th class="row-checkbox">
            </th>
            <th>id</th>
            <th>Username</th>
            <th>Email address</th>
            <th>Institute</th>
            <th>Type File</th>
            <th>Created Date</th>
            <th>File</th>
          </tr>
        </thead>
        <tbody>
          {% for item in files %}
          <tr>
            <td data-id={{ item.id }}>{{ item.id }}</td>
            <td>{{ item.user.username }}</td>
            <td>{{ item.user.email }}</td>
            <td>{{ item.user.institute }}</td>
            <td>
              <div class="block {% if item.type_file == 'PH' %} block-purple
                {% elif item.type_file == 'BI' %} block-success
                {% elif item.type_file == 'SP' %} block-danger
              {% elif item.type_file == 'NU' %} block-warning
              {% elif item.type_file == 'MD' %} block-article
              {% elif item.type_file == 'CH' %} block-secondary {% endif %} ">
                {{ item.get_type_file_display }}
              </div>
            </td>
            <td>{{ item.created_at }}</td>
            <td><a href="{% get_media_prefix %}{{ item.upload }}">{{ item.upload }}</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</main>
{% endblock %}
{% block script %}
<script src="{% static 'profiles/js/file_manage.js' %}"></script>
{% endblock %}

profiles/templates/profiles/files_admin.html
{% extends "profiles/base_admin.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'profiles/css/js.998f9fb9.css' %}">
{% endblock %}
{% block modal %}
<div id="modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <span id="modal-close" class="close">&times;</span>
      </div>
      <div class="modal-body">
        <p class="modal-body-text"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id="modal-close">Close</button>
        <button type="button" class="btn btn-primary" id="modal-save">Confirm</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
<main class="main">
  <div class="main__hero">
    <div class="page">
      <div class="page__title">
        <h2>File Upload</h2>

      </div>
    </div>

    <div class="main__content">
      <div class="upload-form">
        <div id="alert-box"></div>
        <form id="my-form" action="/target" class="dropzone">
          <div style="display: flex; align-items: center;">
            <button id="on-upload" type="button" style="display: none;" value="" class="btn">summit</button>
            <button id="on-remove" type="button" style="display: none; margin-left: 1em;" value=""
              class="btn btn-danger">remove</button>
            <div>
              <input type="radio" name="typeFile" id="PH" value="PH">
              <label for="PH">Physical</label>
              <input type="radio" name="typeFile" id="CH" value="CH">
              <label for="CH">Chemical</label>
              <input type="radio" name="typeFile" id="SP" value="SP">
              <label for="SP">Sampleinfo</label>
              <input type="radio" name="typeFile" id="NU" value="NU">
              <label for="NU">Nutrition</label>
              <input type="radio" name="typeFile" id="BI" value="BI">
              <label for="BI">Bioactive</label>
              <input type="radio" name="typeFile" id="MD" value="MD">
              <label for="MD">Meta Data</label>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}
{% block script %}
<script src="{% static 'profiles/js/file_upload.js' %}"></script>
{% endblock %}

profiles/templates/profiles/users_admin.html
{% extends "profiles/base_admin.html" %}
{% load static %}
{% block modal %}
<div id="modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <span id="modal-close" class="close">&times;</span>
      </div>
      <div class="modal-body">
        <p class="modal-body-text"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id="modal-close">Close</button>
        <button type="button" class="btn btn-primary" id="modal-save">Confirm</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
<main class="main">
  <div class="main__hero">
    <div class="page">
      <div class="page__title">
        <h2>User management</h2>

      </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
    {% endif %}
    <div class="main__content">
      <table class="table">
        <thead>
          <tr>
            <th class="row-checkbox">
            </th>
            <th>id</th>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email address</th>
            <th>Institute</th>
            <th>Date joined</th>
            <th>Active</th>
            <th>Approval</th>
            <th>Super User</th>
            <th>Staff</th>
          </tr>
        </thead>
        <tbody>
          {% for item in users %}
          <tr>
            <td data-id={{ item.user.id }}>{{ item.user.id }}</td>
            <td>{{ item.user.username }}</td>
            <td>{{ item.user.first_name }}</td>
            <td>{{ item.user.last_name }}</td>
            <td>{{ item.email }}</td>
            <td>{{ item.user.institute }}</td>
            <td>{{ item.user.date_joined }}</td>
            <td class="text-center">{% if not item.user.is_active %}
              <div class="block block-danger">No</div>
              {% else %}
              <div class="block block-success">Yes</div>
              {% endif %}
            </td>
            <td class="text-center">{% if not item.verified %}
              <div class="block block-danger">No</div>
              {% else %}
              <div class="block block-success">Yes</div>
              {% endif %}
            </td>
            <td class="text-center">{% if not item.user.is_superuser %}
              <div class="block block-danger">No</div>
              {% else %}
              <div class="block block-success">Yes</div>
              {% endif %}
            </td>
            <td class="text-center">{% if not item.user.is_staff %}
              <div class="block block-danger">No</div>
              {% else %}
              <div class="block block-success">Yes</div>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</main>
{% endblock %}
{% block script %}
<script src="{% static 'profiles/js/action_users.js' %}"></script>
{% endblock %}