profiles/urls.py
from django.urls import path
from .views import(
    AdminPanelUserView,
    AdminPanelFilesView,
    AdminPanelFileManageView,
    rice_upload
)

app_name = 'profiles'

urlpatterns = [
    path('user_management/', AdminPanelUserView.as_view(), name='user-manage'),
    path('file_management/', AdminPanelFileManageView.as_view(), name='file-manage'),
    path('file_upload/', AdminPanelFilesView.as_view(), name='file_upload'),
    path('rice/upload/', rice_upload, name='rice_upload'),

]

rice/urls.py
from django.urls import path
from .views import(

    HomePageView,
    DocsPageView,
    rice_list_view,
    get_data_name,
    get_data_info,
    info_view,
    advanced_search_view,
    comparison_view,
    get_data_comparison_view,
    AboutPageView
)

app_name = 'rice'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('rice_list/',rice_list_view, name="searches"),
    path('get-data/',get_data_name),
    path('info/<int:pk>/',info_view, name="info-view"),
    path('get_data_info/<int:pk>/<str:fieldGroup>/',get_data_info, name ="data-info"),
    path('advanced_search/',advanced_search_view, name ="advanced-search"),
    path('comparison/',comparison_view, name ="comparison"),
    path('get_data_comparison/<str:fieldGroup>/',get_data_comparison_view, ),
    path('about/',AboutPageView.as_view(), name ="about"),
]

ricenutrition/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('admin_panel/', include('profiles.urls')),
    path('', include('rice.urls')),
]+ static(settings.STATIC_URL,
document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rice/models.py
from django.db import models
from django.conf import settings
User = settings.AUTH_USER_MODEL
# Create your models here.
class Files(models.Model):
    BIOACTIVE = 'BI'
    CHEMICAL = 'CH'
    SAMPLEINFO = 'SP'
    NUTRITION = 'NU'
    PHYSICAL = 'PH'
    META_DATA = 'MD'
    TYPE_FILE = [
        (BIOACTIVE, 'Bioactive'),
        (CHEMICAL, 'Chemical'),
        (SAMPLEINFO, 'Sampleinfo'),
        (NUTRITION, 'Nutrition'),
        (PHYSICAL, 'Physical'),
        (META_DATA, 'Meta Data'),
    ]
    type_file = models.CharField(
        max_length=2,
        choices=TYPE_FILE
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    upload = models.FileField(upload_to='rice/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

rice/forms.py
from django import forms
from django.forms import formset_factory


SELECT_FIELD_CHOICES = [
    ('riceVarietiesTH', 'Rice varieties (TH)'),
    ('riceVarietiesEN', 'Rice varieties'),
    ('cropSiteProvince', 'Crop Site - Province'),
    ('yearOfAnalysis', 'Year of analysis'),
    ('siteOfAnalysis', 'Site of analysis'),
    ('dataSource', 'Data source'),
    ('riceCategories', 'Rice categories'),
    ('length', 'Length '),
    ('color', 'Color'),
    ('chalkiness', 'Chalkiness'),
    ('amylose', 'Amylose'),
    ('content2AP', '2AP content '),
    ('carbohydrate', 'Carbohydrate'),
    ('protein', 'Protein'),
    ('totalFat', 'Total fat'),
]

CONDITION_CHOICES = [
    ('eq', 'Equal to'),
    ('gt', 'Greater than'),
    ('lt', 'Less Than'),
    ('ct', 'Contains'),
    ('bw', 'Begins with'),
    ('ew', 'Ends with'),
    ('ne', 'Not Equal to'),
]
OPERATION_CHOICES = [('and','AND'),('or','OR')]

class AdcancedSearchForm(forms.Form):
    select_field = forms.CharField(
        required=True,
        label='select field',
        widget=forms.Select(choices=SELECT_FIELD_CHOICES,attrs={
            'class':'form-select'
        })
    )
    Condition = forms.CharField(
        required=True,
        label='Condition',
        widget=forms.Select(choices=CONDITION_CHOICES,attrs={
            'class':'form-select'
        })
    )
    operation = forms.CharField(
        required=True,
        widget=forms.Select(choices=OPERATION_CHOICES,attrs={
            'class':'form-select'
        })
    )
    Keyword = forms.CharField(max_length=250,
    label='Keyword',
    widget=forms.TextInput(attrs={
            'class':'form-text'
        })
    )
AdcancedSearchFormSet = formset_factory(AdcancedSearchForm, extra=1)

rice/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import AdcancedSearchFormSet,SELECT_FIELD_CHOICES,CONDITION_CHOICES
from django.conf import settings
from django.http import HttpResponse, request
from django.template.loader import get_template
from xhtml2pdf import pisa
from .utils import get_collection_handle, get_db_handle, special_characters, count_categories, get_data_from_mongo, get_sample_data

@method_decorator(login_required, name='dispatch')
class HomePageView(TemplateView):
    template_name = "rice/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        db, _ = get_db_handle(settings.DB_NAME, settings.HOST_MONGODB)
        collection = get_collection_handle(db, settings.COLLECTION_NAME)
        cursor = collection.find()
        list_cur = list(cursor)
        rice_categories_count = count_categories(list_cur)
        context['rice_categories_count'] = rice_categories_count
        return context

@method_decorator(login_required, name='dispatch')
class DocsPageView(TemplateView):
    template_name = "rice/docs.html"

def render_pdf_view(request):
    template_path = 'rice/pdf.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html.encode('utf-8'), dest=response,)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

@login_required
def rice_list_view(request):
    db, _ = get_db_handle(settings.DB_NAME, settings.HOST_MONGODB)
    collection = get_collection_handle(db, settings.COLLECTION_NAME)
    cursor = collection.find()
    if request.method == 'GET':
        search_form = request.GET.get('search-form', None)
        fiter_form = request.GET.get('fiter-form', None)
        sample_list = list()
        if search_form == 'home':
            query = request.GET.get('q', None)
            if query != None:
                query = special_characters(query)
            else:
                query = ''

            cursor = collection.find({'$or':[
                {"Sampleinfo.riceVarietiesEN": {'$regex': query} },
                {"Sampleinfo.riceVarietiesTH": {'$regex': query} },
                {"Sampleinfo.cropSiteProvince": {'$regex': query} },
                {"Sampleinfo.yearOfAnalysis": {'$regex': query} },
                {"Sampleinfo.siteOfAnalysis": {'$regex': query} },
                {"Sampleinfo.dataSource": {'$regex': query} }
                ]})
            list_cur = list(cursor)
            rice_categories_count = count_categories(list_cur)

            for item in list_cur:
                sample_list.append(item['Sampleinfo'])
            context = {'result':sample_list, 'rice_categories_count':rice_categories_count, 'q_serach':query}
        elif fiter_form != None:
            categories = {
            'Paddy rice':'ข้าวเปลือก',
            'Unmilled rice':'ข้าวกล้อง',
            'Milled rice':'ข้าวสาร',
            'Parboiled rice':'ข้าวนึ่ง',
            'Germinated rice':'ข้าวกล้องงอก',
            'Milk-stage rice':'ข้าวเม่า',
            'Cooked white rice':'ข้าวขาวสุก'
            }
            query = request.GET.get('q', None)
            select_field = request.GET.getlist('select_field', None)
            riceCat = [{'Physical.riceCategories' : categories[i] } for i in select_field]
            if riceCat and query:
                cursor = collection.find({'$and':[{ '$and': riceCat },
                {'$or':[
                    {"Sampleinfo.riceVarietiesEN": {'$regex': query} },
                    {"Sampleinfo.riceVarietiesTH": {'$regex': query} },
                    {"Sampleinfo.cropSiteProvince": {'$regex': query} },
                    {"Sampleinfo.yearOfAnalysis": {'$regex': query} },
                    {"Sampleinfo.siteOfAnalysis": {'$regex': query} },
                    {"Sampleinfo.dataSource": {'$regex': query} }
                ]}]})
            elif query:
                cursor = collection.find({'$or':[
                {"Sampleinfo.riceVarietiesEN": {'$regex': query} },
                {"Sampleinfo.riceVarietiesTH": {'$regex': query} },
                {"Sampleinfo.cropSiteProvince": {'$regex': query} },
                {"Sampleinfo.yearOfAnalysis": {'$regex': query} },
                {"Sampleinfo.siteOfAnalysis": {'$regex': query} },
                {"Sampleinfo.dataSource": {'$regex': query} }
                ]})
            elif riceCat:
                cursor = collection.find({ '$and': riceCat })
            else:
                cursor = collection.find()
            list_cur = list(cursor)
            rice_categories_count = count_categories(list_cur)

            for item in list_cur:
                sample_list.append(item['Sampleinfo'])
            context = {'result':sample_list, 'rice_categories_count':rice_categories_count, 'select_field':select_field, 'q_serach':query}
        else:
            cursor = collection.find()
            list_cur = list(cursor)
            rice_categories_count = count_categories(list_cur)

            for item in list_cur:
                sample_list.append(item['Sampleinfo'])
            context = {'result':sample_list, 'rice_categories_count':rice_categories_count}
    else:
        formset = AdcancedSearchFormSet(request.POST)
        if formset.is_valid():
            coll = {'riceVarietiesTH':'Sampleinfo', 'riceVarietiesEN':'Sampleinfo', 'cropSiteProvince':'Sampleinfo',
            'yearOfAnalysis':'Sampleinfo', 'siteOfAnalysis':'Sampleinfo', 'dataSource':'Sampleinfo', 'riceCategories':'Physical',
            'length':'Physical', 'color':'Physical', 'chalkiness':'Physical', 'amylose':'Chemical', 'content2AP':'Chemical',
            'carbohydrate':'Nutrition', 'protein':'Nutrition', 'totalFat':'Nutrition'}
            cond = {'eq':'$eq', 'gt':'$gt', 'lt':'$lt', 'ct':'$regex', 'bw':'$regex', 'ew':'$regex', 'ne':'$ne'}
            advanced_search = []
            queryOp1 = []
            queryOp2 = []
            for form in formset:
                select_field = form.cleaned_data.get('select_field')
                condition = form.cleaned_data.get('Condition')
                keyword = form.cleaned_data.get('Keyword')
                operation = form.cleaned_data.get('operation')
                advanced_search.append(
                    {
                    'select_field':dict(SELECT_FIELD_CHOICES).get(select_field),
                    'condition':dict(CONDITION_CHOICES).get(condition),
                    'keyword':keyword,
                    'operation':operation
                    })
                if condition == 'ct':
                    keyword = special_characters(keyword)
                    query = {f'{coll[select_field]}.{select_field}': {cond[condition]: f'{keyword}'}}
                elif condition == 'bw':
                    keyword = special_characters(keyword)
                    query = {f'{coll[select_field]}.{select_field}': {cond[condition]: f'^{keyword}'}}
                elif condition == 'ew':
                    keyword = special_characters(keyword)
                    query = {f'{coll[select_field]}.{select_field}': {cond[condition]: f'{keyword}$'}}
                else:
                    query = {f'{coll[select_field]}.{select_field}': {cond[condition]: keyword}}

                if operation == 'and':
                    queryOp1.append(query)
                else:
                    queryOp2.append(query)

            if len(queryOp2) == 0 :
                cursor = collection.find({'$and': queryOp1})
            elif len(queryOp1) == 0 :
                cursor = collection.find()

            else:
                qs = [{'$and': queryOp1}]
                qs.extend(queryOp2)
                cursor = collection.find({'$or': qs})
            list_cur = list(cursor)
            rice_categories_count = count_categories(list_cur)
            sample_list = list()
            for item in list_cur:
                sample_list.append(item['Sampleinfo'])
            context = {'result':sample_list, 'rice_categories_count':rice_categories_count,'advanced_search':advanced_search}
        else:
            return redirect('rice:advanced-search')
    return render(request, 'rice/results.html', context)

@login_required
def get_data_name(request):
    if request.is_ajax():
        db, _ = get_db_handle(settings.DB_NAME, settings.HOST_MONGODB)
        collection = get_collection_handle(db, settings.COLLECTION_NAME)
        cursor = collection.find()
        data = []
        for item in list(cursor):
            data.append(item['Sampleinfo']['riceVarietiesTH'])
            data.append(item['Sampleinfo']['riceVarietiesEN'])

        data = list(set(data))
        return JsonResponse({'data':data})
    return JsonResponse({
        'status_code': 404,
        'error': 'The resource was not found'
    })

@login_required
def get_data_info(request, pk, fieldGroup):
    if request.is_ajax():
        list_item = get_data_from_mongo(pk, fieldGroup)

        return JsonResponse(list_item, safe=False)
    return JsonResponse({
        'status_code': 404,
        'error': 'The resource was not found'
    })

@login_required
def info_view(request, pk):
    Sampleinfo = get_sample_data(pk)

rice/templates/rice/advanced_search.html
{% extends "rice/base.html" %}
{% load static %}
{% block content %}
<div class="container">

  <div class="content b-sd p-2">
    <div class="">
      <h1>Advanced Search</h1>
    </div>
    <form id="form-container" class="flex" style="flex-direction: column; align-items: flex-start; margin: 0 auto;
    max-width: 900px" action="{% url 'rice:searches' %}" method="post" action="">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
      <div class="flex flex-ai-fe mb-1" id="group">
        <div>
          <label class="form-label">{{ form.select_field.label }}</label>
          {{ form.select_field }}
        </div>
        <div class="ml-1">
          <label class="form-label">{{ form.Condition.label }}</label>
          {{ form.Condition }}
        </div>
        <div class="ml-1">
          <label class="form-label">{{ form.Keyword.label }}</label>
          {{ form.Keyword }}
        </div>
        <div class="ml-1">
          {{ form.operation }}
        </div>
        <div class="group-btn ml-1" id="btn-manage">
          <button class="btn-circle" id="add-form" type="button"><span class="success"
              style="line-height: 52px">+</span></button>
          <!-- <button class="btn-circle" id="delete-form" type="button"><span class="danger">-</span></button> -->
        </div>
      </div>
      {% endfor %}
      <div class="group-btn" id="end-form" style="align-self: flex-end;">
        <button type="button" class="btn btn-danger" id="reset-form" disabled>Reset</button>
        <button type="submit" id="btn-submit" class="btn btn-primary">Search</button>
      </div>
    </form>
  </div>
</div>
<script>
  let advancedSearchForm = document.querySelectorAll("#group")
  let container = document.querySelector("#form-container")
  const addButton = document.querySelector("#add-form")

  const resetButton = document.querySelector("#reset-form")
  const endForm = document.querySelector("#end-form")
  let formNum = advancedSearchForm.length - 1
  let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
  const formRegex = RegExp(`form-(\\d){1}-`, 'g')

  addButton.addEventListener('click', addForm)
  function addForm(e) {
    e.preventDefault()
    const btnManage = document.querySelector("#btn-manage")
    btnManage.remove()

    let newForm = advancedSearchForm[0].cloneNode(true) //Clone the bird form

    formNum++ //Increment the form number
    newForm.appendChild(btnManage)
    newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`) //Update the new form to have the correct form number
    container.insertBefore(newForm, endForm) //Insert the new form at the end of the list of forms
    totalForms.setAttribute('value', `${formNum + 1}`)
    resetButton.disabled = false
    const newaddButton = newForm.querySelector("#add-form")
    newaddButton.addEventListener('click', addForm)

  }
  function resetForm(e) {
    e.preventDefault()
    const btnManage = document.querySelector("#btn-manage")
    advancedSearchForm = document.querySelectorAll("#group")
    advancedSearchForm.forEach((element, index) => {
      if (index !== 0) {
        element.remove()
        console.log(advancedSearchForm);
      }
    });
    formNum = 0
    totalForms.setAttribute('value', `${formNum + 1}`)
    resetButton.disabled = true
    advancedSearchForm[0].appendChild(btnManage)
  }
  resetButton.addEventListener('click', resetForm)
</script>
{% endblock content %}

rice/templates/rice/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  {% block extra_head %}
  {% endblock %}
  <title>Thia Rice Nutrition Data</title>
</head>
{% block style %}
{% endblock %}
<style>
  li.current a {
    font-weight: bold;

  }

  li.current a::before {
    background-color: var(--clr-primary-400);

  }
</style>

<body>
  <div class="loader"></div>
  <header class="navbar">
    <div class="navbar__head">
      <div class="navbar__container">
        <a href="/" class="navbar__logo">
          <img src="{% static '/images/logo.png' %}" alt="logo">
          <div class="navbar__logo-text">
            <div>Thai Rice</div>
            <div>Nutrition Data</div>
          </div>
        </a>
        <div class="mobile-menu-btn">
          <img id="mobile-cta" class="mobile-menu" src="{% static '/images/menu.svg' %}" alt="">

        </div>
        <nav class="navbar__menu">
          <img id="mobile-exit" class="mobile-menu-exit" src="{% static '/images/exit.svg' %}" alt="">
          <ul class="primary-nav">
            <li class="{% if "/" == request.path %}current{% endif %}"><a href="{% url 'rice:home' %}">Home</a></li>
            <li class="{% if "/rice_list/" in request.path %}current{% endif %}"><a href="{% url 'rice:searches' %}">Rice
                Lists</a></li>
            <li class="{% if "/advanced_search/" in request.path %}current{% endif %}"><a
                href="{% url 'rice:advanced-search' %}">Advanced Search</a></li>
            <li class="{% if "/about/" in request.path %}current{% endif %}"><a href="{% url 'rice:about' %}">About</a></li>
          </ul>
          <ul class="secondary-nav">
            {% if user.is_authenticated %}
              {% if user.is_staff %}
              <li class="login-cta"><a href="{% url 'profiles:user-manage' %}">Admin Panel</a></li>
              {% endif %}
            <form method="post" action="{% url 'account_logout' %}">
              {% csrf_token %}
              {% if redirect_field_value %}
              <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
              {% endif %}
              <button class="logout-cta" type="submit">Sign Out</button>
            </form>
            {% else %}
            <li class="login-cta"><a href="{% url 'account_login' %}">Login</a></li>
            <li class="singup-cta"><a href="{% url 'account_signup' %}">Signup</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </header>
  {% block content %}
  {% endblock content %}
</body>
<script>
  let preloader = document.querySelector('.loader');
  if (preloader) {
    window.addEventListener('load', () => {
      preloader.remove()
    });
  }

</script>
{% block script %}
{% endblock script %}


</html>

rice/templates/rice/info.html
{% extends "rice/base.html" %}
{% load static %}

{% block extra_head %}
<script src="https://unpkg.com/vega@5.20.2/build/vega.min.js"></script>
<script src="https://unpkg.com/vega-lite@5.1.0/build/vega-lite.min.js"></script>
<script src="https://unpkg.com/vega-lite-api@5.0.0/build/vega-lite-api.min.js"></script>
<script src="https://unpkg.com/vega-tooltip@0.27.0/build/vega-tooltip.min.js"></script>

{% endblock %}
{% block content %}

<div class="container">
  <section class="data-info">
    <div class="data-info__head">
      <h3 class="data-info__title">{{ riceVarieties }}</h3>
      <div class="data-info__option">
        <a class="data-info__option--prev" href="{% url 'rice:info-view' prev %}"> &#60;</a>
        <a class="data-info__option--next" href="{% url 'rice:info-view' next %}"> &#62; </a>
      </div>
    </div>
    <div class="data-info__content">
      {% for key, value in Sampleinfo.items %}
      <div class="data-info__item">
        <p>{{key}}</p>
        <h1>{{ value }}</h1>
      </div>
      {% endfor %}
    </div>
  </section>
  <!--  -->
  <section class="dashboard">
    <nav class="dashboard__menu">
      <ul>
        <li><a id="menu-phy" class="btn-menu" data-field="Physical">Physical</a></li>
        <li><a id="menu-chem" class="btn-menu" data-field="Chemical">Chemical</a></li>
        <li><a id="menu-nutri" class="btn-menu" data-field="Nutrition">Nutrition</a></li>
        <li><a id="menu-bio" class="btn-menu" data-field="Bioactive">Bioactive</a></li>
      </ul>
    </nav>
    <div class="group-table">

    </div>
    <div class="dashboard__chart" id="view"></div>
  </section>
</div>
{{ id|json_script:"id" }}
{% endblock %}
{% block script %}

<script src=" {% static '/rice/js/info.js' %}" defer></script>

{% endblock script %}

rice/templates/rice/results.html
{% extends "rice/base.html" %}
{% load static %}

{% block style %}
<style>
  .w-chip {
    background-color: transparent;
    border: 1px solid rgba(32, 33, 36, .16);
    border-radius: 20px;
    box-sizing: border-box;
    display: block;
    font-size: 1em;
    height: 32px;
    line-height: 30px;
    margin: 0 8px 12px 0;
    overflow: hidden;
    padding: 0 12px;
    text-decoration: none;
    transition: background-color .2s, border .2s;
    text-align: center;
  }

  .w-chip:hover {
    background-color: rgba(32, 33, 36, .04);
    border: 1px solid rgba(32, 33, 36, .2);
  }

  .w-chip-a {
    color: var(--clr-warning-700);
    background-color: var(--clr-warning-100);
    border: 1px solid var(--clr-warning-500);
  }

  .w-chip-b {
    color: var(--clr-article-500);
    background-color: var(--clr-article-100);
    border: 1px solid var(--clr-article-500);
  }
</style>
{% endblock %}
{% block content %}

<div class="grid-sidebar">
  <nav class="sidebar">
    <div class="sidebar__col">
      <form action=".">
        <div style="display: flex; align-items: center; justify-content: center; width: 100%;">
          <input style="width: 100%; padding: 0.75em 0.45em; margin: 0.5em 0.75em; border-radius: 4px; font-size: 1rem;"
            type="text" name="q" value="{% if q_serach %}{{ q_serach }}{% endif %}">
        </div>
        <h6 class="sidebar__heading">
          <span>Rice Categories</span>
        </h6>
        <input type="hidden" name="fiter-form">
        <ul class="sidebar__list">
          {% for key,value in rice_categories_count.items %}
          <li class="sidebar__item">
            <div class="sidebar__input">
              <div>
                <input {% if key in select_field %} checked {% endif %} {% if not value %} disabled {% endif %}
                  type="checkbox" name="select_field" value="{{key}}" onChange="this.form.submit()">
                <span {% if not value %} style="color: var(--clr-neutral-300);" {% endif %}>{{key}}</span>
              </div>
              <div><span>({{value}})</span></div>

            </div>
          </li>
          {% endfor %}
        </ul>
        {% if advanced_search %}
        <h6 class="sidebar__heading">
          <span>Advanced Search</span>
        </h6>
        <div style="display: flex; flex-direction: column; justify-content: center; margin: 0 0.25em;">
          {% for item in advanced_search %}
          <a href=""
            class="w-chip {% if item.operation == 'and' %}w-chip-a{% else %}w-chip-b{% endif %}">{{item.select_field }}
            {{ item.condition }} {{ item.keyword }}</a>
          {% endfor %}
        </div>
        {% endif %}
    </div>
    <div style="display: flex; justify-content: space-around; align-items: center; margin-top: 1em; width: 100%;">

      <button class="btn btn-secondary" type="button"><a href="{% url 'rice:searches' %}"
          style="color: white;">Reset</a></button>
      <button type="submit" class="btn">Search</button>
    </div>
    </form>
  </nav>
  <main class="content">
    <div class="table-content container-lg">
      <table class="table">
        <thead>
          <tr>
            <th class="row-checkbox">
              <div class="ctn-checkbox">
                <input type="checkbox" name="" id="checkall" class="checkbox">
              </div>
            </th>
            <th scope="col">Crop Sample ID</th>
            <th scope="col">Rice varieties (TH)</th>
            <th scope="col">Rice varieties</th>
            <th scope="col">Crop Site - Province</th>
            <th scope="col">Year of analysis</th>
            <th scope="col">Site of analysis</th>
            <th scope="col">Data source </th>
          </tr>
        </thead>
        <tbody>
          {% for data in result %}
          <tr>
            <td><a href="{% url 'rice:info-view' data.cropSampleID %}" data-id={{ data.cropSampleID }}
                style="color: #2470dc;">
                {{ data.cropSampleID}}
              </a>
            </td>
            {% if data.riceVarietiesTH %}
            <td>{{ data.riceVarietiesTH }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if data.riceVarietiesEN %}
            <td><a href="{% url 'rice:info-view' data.cropSampleID %}" style="color: #2470dc;">
                {{ data.riceVarietiesEN}}
              </a>
            </td>
            {% else %}
            <td></td>
            {% endif %}
            {% if data.cropSiteProvince %}
            <td>{{ data.cropSiteProvince }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if data.yearOfAnalysis %}
            <td>{{ data.yearOfAnalysis }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if data.siteOfAnalysis %}
            <td>{{ data.siteOfAnalysis }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if data.dataSource %}
            <td>{{ data.dataSource }}</td>
            {% else %}
            <td></td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </main>
</div>

{% endblock %}
{% block script %}
<script src="{% static '/rice/js/res.js' %}"></script>
{% endblock script %}